config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  root "creative_sessions#index"

  resources :creative_sessions
  resources :locations
end

app/models/creative_session.rb
# == Schema Information
#
# Table name: creative_sessions
#
#  id              :bigint           not null, primary key
#  end_time        :datetime         not null
#  notes           :text
#  recurrence_rule :integer
#  recurring       :boolean
#  start_time      :datetime         not null
#  style           :string           not null
#  title           :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  location_id     :bigint           not null
#
# Indexes
#
#  index_creative_sessions_on_location_id  (location_id)
#  index_creative_sessions_on_start_time   (start_time)
#  index_creative_sessions_on_style        (style)
#
# Foreign Keys
#
#  fk_rails_...  (location_id => locations.id)
#
class CreativeSession < ApplicationRecord
  belongs_to :location

  enum :recurrence_rule, {
    weekly: 0,
    monthly: 1,
    first_sunday: 2,
    last_thursday: 3
  }

  scope :happening_today, -> { where(start_time: Time.current.all_day) }
  scope :upcoming, -> { where("start_time > ?", Time.current).order(start_time: :asc) }

  validates :title, presence: true
  validates :style, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :location, presence: true
end

app/controllers/creative_sessions_controller.rb
class CreativeSessionsController < ApplicationController
  before_action :set_creative_session, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :authorize_user!, only: [ :edit, :update, :destroy ]

  def index
    @today_sessions = CreativeSession.happening_today.includes(:location)
    @upcoming_sessions = CreativeSession.upcoming.includes(:location)
  end

  def show
  end

  def new
    @creative_session = CreativeSession.new
  end

  def create
    @creative_session = CreativeSession.new(creative_session_params)
    assign_location_to_session

    if @creative_session.save
      redirect_to creative_sessions_path, notice: "Session was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    assign_location_to_session

    if @creative_session.update(creative_session_params)
      redirect_to creative_sessions_path, notice: "Session was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @creative_session.destroy
    redirect_to creative_sessions_path, notice: "Session was successfully deleted."
  end

  private

  def set_creative_session
    @creative_session = CreativeSession.find(params[:id])
  end

  def creative_session_params
    params.require(:creative_session).permit(
      :title,
      :style,
      :start_time,
      :end_time,
      :location_id,
      :notes,
      :recurring,
      :recurrence_rule
    )
  end

  def authorize_user!
    return if current_user.admin?
    if current_user.location_user?
      unless @creative_session.location_id == current_user.location_id
        redirect_to creative_sessions_path, alert: "You are not authorized to perform this action."
      end
    else
      redirect_to creative_sessions_path, alert: "You are not authorized to perform this action."
    end
  end

  def assign_location_to_session
    if current_user.location_user?
      @creative_session.location_id = current_user.location_id
    end
  end
end

app/views/creative_sessions/_form.html.erb
<%= turbo_frame_tag "new_location" do %>
<%= simple_form_for @creative_session do |f| %>
  <div class="form-section">
    <%= f.input :title, label: 'Session Title', placeholder: 'e.g., Face melting jam session' %>
    
    <%= f.input :style, 
                collection: ['Electronic', 'Hip-Hop', 'Experimental', 'Neo-Soul', 'R&B', 'Jazz', 'Jam', 'Funk', 'Blues', 'Rock', 'Open', 'Folk', 'Irish', 'Open Mic', 'Classical', 'Comedy', 'Literature', 'Spoken Word', 'Storytelling', 'Poetry', 'Other', 'Killing', 'Burning', 'Lit', 'Lit AF', 'Heavy', 'Profound'],
                prompt: 'Select a style' %>
  </div>

  <div class="form-section">
    <div class="time-inputs">
      <%= f.input :start_time, 
                  html5: true,
                  input_html: { 
                    type: 'datetime-local',
                    min: Date.today 
                  } %>
      
      <%= f.input :end_time, 
                  html5: true,
                  input_html: { 
                    type: 'datetime-local',
                    min: Date.today 
                  } %>
    </div>
  </div>

  <% unless current_user.location_user? %>
    <div class="form-section">
      <div class="location-select-wrapper">
        <%= f.association :location,
                         collection: Location.order(:name),
                         prompt: 'Select a venue',
                         label_method: :display_name %>
        
        <div class="location-actions">
          <span class="location-divider">or</span>
          <%= link_to new_location_path, 
                      class: 'button secondary add-location',
                      data: { turbo_frame: "new_location" } do %>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="icon">
              <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
            </svg>
            Add New Venue
          <% end %>
        </div>
      </div>
    </div>
  <% else %>
    <%= f.hidden_field :location_id, value: current_user.location_id %>
  <% end %>

  <div class="form-section">
    <%= f.input :notes, 
                as: :text,
                placeholder: 'Additional details about the session...' %>
  </div>

  <div class="form-section recurrence-section">
    <%= f.input :recurring, 
                as: :boolean,
                input_html: { data: { action: "change->session#toggleRecurrence" } } %>

    <div data-session-target="recurrenceOptions" class="hidden">
      <%= f.input :recurrence_rule,
                  collection: CreativeSession.recurrence_rules.keys.map { |rule| 
                    [rule.titleize, rule]
                  },
                  include_blank: false %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'button primary' %>
    <%= link_to 'Cancel', creative_sessions_path, class: 'button secondary' %>
    </div>
  <% end %>
<% end %> 

app/views/creative_sessions/_location_select.html.erb
<div class="location-select-wrapper" id="session_location_id">
  <%= f.association :location,
                   collection: Location.order(:name),
                   prompt: "Select a venue",
                   selected: f.object.location_id %>
  
  <div class="location-actions">
    <span class="location-divider">or</span>
    <%= link_to new_location_path, 
                class: 'button secondary add-location',
                data: { turbo_frame: "new_location" } do %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="icon">
        <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
      </svg>
      Add New Venue
    <% end %>
  </div>
</div> 

app/views/creative_sessions/edit.html.erb
<div class="container">
  <h1>Edit Jam Session</h1>
  
  <%= render 'form' %>
</div> 

app/views/creative_sessions/index.html.erb
<div class="container">
  <h1>Jam Sessions in the Capital Region</h1>

  <section class="today-sessions">
    <h2>Today's Sessions</h2>
    <div class="sessions-grid">
      <% @today_sessions.each do |session| %>
        <%= render CreativeSessionCardComponent.new(creative_session: session) %>
      <% end %>
    </div>
  </section>

  <section class="upcoming-sessions">
    <h2>Upcoming Sessions</h2>
    <div class="sessions-grid">
      <% @upcoming_sessions.each do |session| %>
        <%= render CreativeSessionCardComponent.new(creative_session: session) %>
      <% end %>
    </div>
  </section>

  <% if user_signed_in? %>
    <%= link_to "Add New Session", new_creative_session_path, class: "button primary" %>
  <% end %>
</div> 

app/views/creative_sessions/new.html.erb
<div class="container">
  <h1>Create New Jam Session</h1>
  
  <%= render 'form' %>
</div> 

app/views/creative_sessions/show.html.erb
<div class="creative-session-show">
  <div class="creative-session-show-header">
    <h1><%= @creative_session.title %></h1>
    <div class="actions">
      <% if user_signed_in? && (current_user.admin? || current_user.location_id == @creative_session.location_id) %>
        <%= link_to 'Edit', edit_creative_session_path(@creative_session), class: 'button secondary' %>
        <%= button_to 'Delete', creative_session_path(@creative_session), 
                    method: :delete, 
                    class: 'button danger',
                    data: { turbo_confirm: 'Are you sure?' } %>
      <% end %>
      <%= link_to 'Back', creative_sessions_path, class: 'button' %>
    </div>
  </div>

  <div class="creative-session-show-content">
    <div class="creative-session-info-panel">
      <div class="creative-session-style">
        <%= @creative_session.style %>
      </div>

      <div class="creative-session-datetime">
        <h3>When</h3>
        <p class="date"><%= @creative_session.start_time.strftime("%A, %B %d, %Y") %></p>
        <p class="time">
          <%= @creative_session.start_time.strftime("%I:%M %p") %> - 
          <%= @creative_session.end_time.strftime("%I:%M %p") %>
        </p>
      </div>

      <div class="creative-session-venue">
        <h3>Where</h3>
        <h4><%= @creative_session.location.name %></h4>
        <p><%= @creative_session.location.address %></p>
        <p><%= @creative_session.location.city %>, <%= @creative_session.location.state %> <%= @creative_session.location.zip_code %></p>
      </div>

      <% if @creative_session.notes.present? %>
        <div class="creative-session-notes">
          <h3>Additional Notes</h3>
          <%= simple_format @creative_session.notes %>
        </div>
      <% end %>
    </div>

    <div class="map-container" 
         data-controller="map"
         data-map-latitude-value="<%= @creative_session.location.latitude %>"
         data-map-longitude-value="<%= @creative_session.location.longitude %>"
         data-map-name-value="<%= @creative_session.location.name %>">
    </div>
  </div>
</div> 