config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  root "creative_sessions#index"

  resources :creative_sessions
  resources :locations
end

app/views/layouts/active_admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Admin" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "active_admin", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="active_admin">
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Cr Sessions" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "active_admin", "data-turbo-track": "reload" if controller_path =~ /admin\// %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Rails.application.credentials.dig(:google_maps, :api_key)}&libraries=places", defer: true %>
  </head>

  <body>
    <% if notice %>
      <p class="alert notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <% if user_signed_in? %>
      <p>
        Logged in as <%= current_user.email %> |
        <%= link_to 'Edit Profile', edit_user_registration_path %> |
        <%= button_to 'Logout', 
                      destroy_user_session_path, 
                      method: :delete,
                      class: 'button secondary' %>
      </p>
    <% else %>
      <%= link_to 'Login', new_user_session_path %> |
      <%= link_to 'Sign up', new_user_registration_path %>
    <% end %>

    <%= yield %>
  </body>
</html>